services:
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=test_value
    volumes:
      - ./web:/web
    tty: true
    restart: always
    depends_on:
      - db
    networks:
      - matrix_network

  matrix_whale:
    build:
      context: ./matrix_whale
    environment:
      - ENV_VAR=test_value
    ports:
      - "6000:6000"
    tty: true
    restart: always
    volumes:
      - ./matrix_whale:/matrix_whale
    depends_on:
      - db
    networks:
      - matrix_network

  noaa_adapter:
    build:
      context: ./noaa_adapter
    environment:
      - ENV_VAR=test_value
    tty: true
    restart: always
    volumes:
      - ./noaa_adapter/app:/app
    depends_on:
      - db
    networks:
      - matrix_network

  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tty: true
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - matrix_network

volumes:
  db_data:

networks:
  matrix_network:
    driver: bridge