name = "matrix_whale"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 2.0.0"
wisp = ">= 1.1.0 and < 2.0.0"
mist = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_otp = ">= 0.12.0 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gzlib = ">= 1.0.1 and < 2.0.0"
decode = ">= 0.2.1 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
pog = ">= 1.0.1 and < 2.0.0"
gleam_yielder = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
