name = "matrix_whale"
version = "1.0.0"
gleam = ">= 1.1.0"

[dependencies]
gleam_stdlib = ">= 0.50.0 and < 2.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
mist = ">= 5.0.0 and < 6.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gzlib = ">= 1.0.1 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
pog = ">= 4.0.0 and < 5.0.0"
gleam_yielder = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
