name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test (OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        otp: ["26.2.5", "27.3.4"]
        gleam: ["1.12.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          gleam-version: ${{ matrix.gleam }}
          rebar3-version: "3"

      - name: Cache Gleam dependencies
        uses: actions/cache@v4
        with:
          path: |
            matrix_whale/matrix_whale/build/packages
            matrix_whale/matrix_whale/build/dev
            ~/.hex
          key: ubuntu-gleam-${{ matrix.otp }}-${{ hashFiles('matrix_whale/matrix_whale/manifest.toml', 'matrix_whale/matrix_whale/gleam.toml') }}
          restore-keys: |
            ubuntu-gleam-${{ matrix.otp }}-
            ubuntu-gleam-

      - name: Update dependencies
        run: gleam update
        working-directory: matrix_whale/matrix_whale

      - name: Build project
        run: gleam build
        working-directory: matrix_whale/matrix_whale

      - name: Run tests
        run: gleam test
        working-directory: matrix_whale/matrix_whale

      - name: Check formatting
        run: gleam format --check src test
        working-directory: matrix_whale/matrix_whale
