name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test (OTP ${{ matrix.otp }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    
    strategy:
      matrix:
        include:
          # Ubuntu tests with multiple OTP versions
          - otp: "26.2.5"
            gleam: "1.8.0"
            os: "ubuntu-latest"
          - otp: "27.3.4"  
            gleam: "1.8.0"
            os: "ubuntu-latest"
          # macOS 14 (stable) with compatible versions
          - otp: "27.3.4"
            gleam: "1.8.0"
            os: "macos-14"
          # Windows with compatible versions
          - otp: "27.3.4"
            gleam: "1.8.0"
            os: "windows-latest"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          gleam-version: ${{ matrix.gleam }}
          rebar3-version: "3"
      
      - name: Cache Gleam dependencies
        uses: actions/cache@v4
        with:
          path: |
            build/packages
            build/dev
            ~/.hex
          key: ${{ runner.os }}-gleam-${{ matrix.otp }}-${{ hashFiles('**/manifest.toml', '**/gleam.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-${{ matrix.otp }}-
            ${{ runner.os }}-gleam-
      
      - name: Download dependencies
        run: gleam deps download
      
      - name: Build project
        run: gleam build
      
      - name: Run tests
        run: gleam test
      
      - name: Check formatting
        run: gleam format --check src test
